[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'artifacts/contracts'
libs = ['lib']
no_match_path = "contracts/*"
solc_version = '0.8.18'
optimizer = true
optimizer_runs = 18_000
viaIR = false
eth_rpc_url = "https://api.s0.b.hmny.io"

[profile.test]
fork_block_number = 17237181

[profile.ci_sizes]
optimizer_runs = 18_000
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
# temporary workaround while we figure out perf issues + configure different test sets + profiles
runs = 5
max_test_rejects = 9_999_999
[rpc_endpoints]
sepolia = 'https://eth-sepolia.g.alchemy.com/v2/kw-ycolm1dq00fqT_Y-b-FkV-Ai6h38m'
anvil = 'http://127.0.0.1:8545'
